---

- name: install prerequisites
  package: name={{ item }} state=present
  with_items:
    - "java"
    - "tomcat"
    - "maven"
    - "ant"

- name: Do a bad thing
  command: setenforce 0
  run_once: true
